sudo: required
language: cpp
compiler: g++

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"



script: 
       ./gradlew runPyTest

