language: cpp
compiler: g++


install:
   - git clone git@github.com:$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
   - cd $TRAVIS_REPO_SLUG
   - git checkout -qf $TRAVIS_COMMIT



script: 
   - ./gradlew runPyTest

